name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Verify Forge installation
        run: forge --version

      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: stable

      - uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - run: |
          cargo build
